# Generated by Django 5.1.5 on 2025-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Заголовок'),
        ),
    ]
